on:
  workflow_dispatch:
  # Disable to start running
  # schedule:
  #   - cron: '0 */3 * * *' # runs every 3 hours

jobs:
  pull_and_upload_files:
    name: Pull and Upload Files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies

    - run: pip install -r requirements.txt

    - name: Run Main Script
      run: python main.py
      env:
        ADDON_NAME: ${{ secrets.ADDON_NAME }} 

    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY.MM.DD.HH.mm

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: v${{ steps.current-time.outputs.formattedTime }}
        name: v${{ steps.current-time.outputs.formattedTime }}
        draft: false
        prerelease: false
        artifacts: "*.zip"
        artifactContentType: application/zip
        token: ${{ secrets.GITHUB_TOKEN }}
